### ISSUE TITLE
Aggiungere il supporto per "moretrees" di VanessaE

### ISSUE THREAD

**Issue by H4mlet** [H4mlet/fallen_trees#1]
[moretrees](https://github.com/minetest-mods/moretrees) di [VanessaE](https://github.com/VanessaE)

Usato nel server Minetest Italia di CarlBishop

@peppinoita @pandaro

**Comment by H4mlet** [comment]
Il supporto funziona malamente a causa delle dimensioni degli alberi:

- la presenza di nodi-tronco tra le foglie impedisce il decadimento della parte superiore degli alberi
- l'aggiunta delle foglie al gruppo falling (per risolvere il problema precedente) provoca un effetto domino che si estende agli alberi adiacenti, creando un altro problema

A titolo di cronaca, allego il codice necessario per il supporto.

[moretrees.txt](https://github.com/H4mlet/fallen_trees/files/1668894/moretrees.txt)

**Comment by pandaro** [comment]
Ci ho dato un'occhiata ma, non credo sia una buona idea, non si riesce a fare un buon lavoro solo utilizzando fallen nodes, idea da scartare, risulta un lavoro fatto male.
Se si vuole farlo bene si può utilizzare "find_node_near" ma è pericoloso perchè è difficile distinguere albero da albero e si rischia di far cadere tuttta la foresta.
Ma semplicemente lasciarlo com'è? o piuttosto ci sono dei mod macchina per semplificare sta roba, o ancora meglio mod commerciali.
Tipo che c'è un prezzo per la roba e se te la vendo faccio i soldi, chiaramente.
Poi chi è admin sto problema non lo ha...

**Comment by H4mlet** [comment]
> Ci ho dato un'occhiata ma, non credo sia una buona idea, non si riesce a fare un buon lavoro solo utilizzando fallen nodes, idea da scartare, risulta un lavoro fatto male.

Concordo.

> Se si vuole farlo bene si può utilizzare "find_node_near" ma è pericoloso perchè è difficile distinguere albero da albero e si rischia di far cadere tuttta la foresta.

Esatto, e anche limitando il raggio d'azione a quattro o cinque nodi attorno al tronco o ai rami dubito che funzionerebbe a dovere: i tipi di albero sono una dozzina, bisognerebbe creare regole su misura per ciascun tipo.

>Ma semplicemente lasciarlo com'è? o piuttosto ci sono dei mod macchina per semplificare sta roba, o ancora meglio mod commerciali.
Tipo che c'è un prezzo per la roba e se te la vendo faccio i soldi, chiaramente.
Poi chi è admin sto problema non lo ha...

Penso che il server per quanto riguarda gli alberi possa restare così com'è: aggiungere un modulo che lavora male o crea problemi è peggio che avere qualche cima d'albero che fluttua.

**Comment by pandaro** [comment]
esatto, poi se tu consideri, idea mia.
mod commerciale, ogni cosa ha un prezzo e nel negozio dell'admin c'è un posto dove tu vai a portare la roba e ti viene pagata, la gente è invogliata a portare i materiali in eccesso, quind a ripulire.

**Comment by H4mlet** [comment]
> mod commerciale, ogni cosa ha un prezzo e nel negozio dell'admin c'è un posto dove tu vai a portare la roba e ti viene pagata, la gente è invogliata a portare i materiali in eccesso, quind a ripulire.

nel server ci sono le vending machines, perciò la tua idea è fattibile; il problema è che quegli alberi (sequoie, querce, ecc.) per essere rimossi completamente richiedono tempo. l'utente medio taglia il tronco e lascia il resto dov'è, non potendo volare.

ho una idea a riguardo, la propongo sul git del server e chiudo questo thread: teniamo tutte le discussioni sul server nel git del server
